name: sheetmusicarchive

channels:
    - defaults
    - conda-forge

dependencies:
    - python=3.10   
    - numpy
    - pandas
    - matplotlib
    - pip
    - pip:
        - easyocr
        - pypdf
